### ISSUE TITLE
Changes needed before December 6

### ISSUE THREAD

**Issue by ddaddy** [nicolasgomollon/AppSales-Mobile#18]
Apple says they are killing the Autoingestion tool that we use to download reports in November.
They have a new command line utility called Reporter.

Reporter also allows the download of payment information, so if we transition to reporter we can get the payments working again.

**Comment by nicolasgomollon** [comment]
Thanks for the heads up! I’ve already mapped out all of the necessary API calls to make this happen, but just need to make the necessary code changes to ensure that everything remains compatible. Stay tuned for an update with these changes…

**Comment by sirnacnud** [comment]
Any progress on this? It looks like the old API now returns an error message saying to use the new `Reporter` tool and reports don't download.

**Comment by futuretap** [comment]
Do you need help reverse-engineering the network protocol `Reporter.jar` uses? Or is this already published somewhere?

**Comment by nicolasgomollon** [comment]
Hey everyone,

I apologize for the delay, it’s been an overwhelmingly busy past couple of months, and simply haven’t found the time to get to work on this. The latest commit (c601d561bc1a01014b4f742ffc6d08c624da08ac) replaces the Autoingestion API with the Reporter API for the “Sales and Trends” reports.

I’ve replaced just the necessary code to get it working properly for now, but part of the app needs an overhaul to take advantage of all of the features the Reporter API provides. For example, the code could be improved by fetching the Vendor IDs from the `Sales.getVendors` command prior to using the `Sales.getReport` command. With this in place, we could in theory get rid of the need to input a Vendor ID during account setup.

I haven’t yet looked into using the Reporter API to download the “Payments and Financial” reports, but it still works, albeit using the undocumented iTunes Connect JSON API.

For reference, the Reporter API is documented [here](https://help.apple.com/itc/appsreporterguide/), in case anyone wants to take a look at it.

I’ll close this issue, since it’s now fixed, and I’ve opened a new one to continue migration to the new Reporter API (#22).

Thanks again for your patience,
–Nico

**Comment by ddaddy** [comment]
Unbelievable. I have just spend the last 15 minutes doing the exact same thing and was just this minute trying to figure out how to update my fork so I could push it and make a pull request.

Well done, and thank you.

**Comment by nicolasgomollon** [comment]
It looks like this is working on the simulator, but I’m unable to get it working on my device with my existing data.

It looks like [after this line](https://github.com/nicolasgomollon/AppSales-Mobile/tree/89dc553f3d54dc0872b5f379033c425dad6e11da/Classes/ReportDownloadOperation.m#L176), `[response.MIMEType isEqualToString:@"text/html"]`, and I’m getting the following in `reportData`:
```html
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>Shield</center>
</body>
</html>
```

Funny thing is, this is working just fine on a clean install in the simulator. I will have to take a closer look at it later, unless someone else wants to see if they can debug this one.

**Comment by nicolasgomollon** [comment]
Okay, commit f67434291c62987eb3b05db7deb25ba1278fca28 should finally get this one fixed. Please check it out, and let me know if you guys are still running into issues.

**Comment by sirnacnud** [comment]
I'm still getting the same HTML 403 error when trying on my device.

**Comment by nicolasgomollon** [comment]
@sirnacnud Please check out the latest commit 730937033797c50fe01276b74c0855648b105c3f to see if that fixes the issue. I replaced the app container on my device with a copy from a few days ago, and started running into the same issue again. It turns out that we actually have to clear any stored cookies before making requests to the Reporter API. There must be some cookie that messes with the way the API works, but making requests from a clean slate solves the problem.

**Comment by sirnacnud** [comment]
Thanks for the quick fix. I am now able to download the reports. I did happen to notice the below error message when downloading the weekly report.

    AppSalesMobile[3794:1014524] Downloaded report has incorrect date, ignoring
