### ISSUE TITLE
Fiscal dates incorrect

### ISSUE THREAD

**Issue by ddaddy** [nicolasgomollon/AppSales-Mobile#25]
I think the fiscal dates are incorrect for December 16 and January 17.
I'm seeing a much lower total for December and a higher total than I should for January.

Here's the fiscal calendar https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wa/jumpTo?page=fiscalcalendar

**Comment by nicolasgomollon** [comment]
Nice catch! It turns out that December in Apple’s Fiscal Calendar has 5 weeks when `(year - 1)` is divisible by 5.

This also occurred in 2011, but the fix was hard-coded in only for December 2011 (see [here](https://github.com/nicolasgomollon/AppSales-Mobile/commit/fb14f9bae3e60e1fa227a2855b07b2db4737336a)), rather than fixing the underlying issue.

Commit 00854284e63adfc8b764173507f10e3cefc4326f should take care of this case from now on.
