### ISSUE TITLE
Reporter auth moving to tokens

### ISSUE THREAD

**Issue by jasondmichaelson** [nicolasgomollon/AppSales-Mobile#29]
You can now access Reporter by generating a unique access token instead of using your Apple ID
password. Starting in August 2017, you will no longer be able to sign in to Reporter with your
Apple ID password or app-specific passwords.
So looks like we have until August before we need to start logging into Reporter w/ generated tokens instead of our iTunes Connect password. :o

This is a duplicate of issue 291 in the omz repository.

**Comment by ddaddy** [comment]
I've tried using a reporter Auth token instead of the App Specific token and it doesn't work. I'm guessing the parameter has a different name.

**Comment by Morpheus2002** [comment]
Can't download reports for a few days. According to the issue from main repo (https://github.com/omz/AppSales-Mobile/issues/292#issuecomment-317265536) we need to use ITC AccesToken.

**Comment by nicolasgomollon** [comment]
@Morpheus2002 Report downloads are working just fine over here. Please make sure you’re using the latest build 2.4 (669) from commit 3af6fa056f7e0249473c8dedeb621849b632819a.

**Comment by Morpheus2002** [comment]
@nicolasgomollon yes, I am on the latest version.

**Comment by dave256** [comment]
It's been working for me, but I expect it to stop soon as they will be requiring the access token method instead of username/password. I generated an access token by logging on to the iTunes Connect website using my computer but then AppSales would no longer download them using my password. I followed the instructions from the above linked omz#292 comment and changed the code to put "accesstoken" in the dictionary and then entered my generated access token in the password field in the app and it works.

**Comment by dave256** [comment]
See: https://github.com/dave256/AppSales-Mobile/commit/b3c53323ca3edb85da3455df7afc6f906ffcbc2b

**Comment by sirnacnud** [comment]
The app is definitely going to need to be updated to request an access token from the user instead of an user/password or app-specific password.

**Comment by nicolasgomollon** [comment]
@Morpheus2002 As noted in the [Reporter User Guide](https://help.apple.com/itc/appsreporterguide/#/apd2f1f1cfa3), `Once you generate an access token, you won't be able to log in to Reporter with your username and password.`, so you were most likely unable to download reports for this reason.

**Comment by nicolasgomollon** [comment]
Commit 52b21d44bea6d591fc20c99769e927b6d42c90ed takes care of this issue. The `Account` → `iTunes Connect Login` page has been updated to replace the App-Specific Password section with an Access Token section that allows you to either get an existing access token or generate a new one, as needed.

As noted in the commit message, although the Reporter API now uses an access token in place of a password, an actual iTunes Connect email address and password is still required in order to download Payments via the undocumented iTunes Connect JSON API.
